# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-12 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ballot_record',
            fields=[
                ('ballot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('balloters_name', models.CharField(max_length=100)),
                ('ballotees_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ballot Record',
                'verbose_name_plural': 'Ballot Records',
            },
        ),
    ]
